name = "mr-flare"
main = "./dist/index.mjs"
workers_dev = true
compatibility_date = "2022-08-07"
compatibility_flags = []

routes = [{ pattern = "discord.jacobmgevans.com", custom_domain = true }]

[build]
command = "node scripts/build.js production"

[env.development.build]
command = "node scripts/build.js development"

[env.development.build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
global_async_io = true
